---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - const-forecaster.k8s-cf.io
  resources:
  - costforecasters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - const-forecaster.k8s-cf.io
  resources:
  - costforecasters/finalizers
  verbs:
  - update
- apiGroups:
  - const-forecaster.k8s-cf.io
  resources:
  - costforecasters/status
  verbs:
  - get
  - patch
  - update
