//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Akash Pathak <pathakvikash9211@gmail.com>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostForecaster) DeepCopyInto(out *CostForecaster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostForecaster.
func (in *CostForecaster) DeepCopy() *CostForecaster {
	if in == nil {
		return nil
	}
	out := new(CostForecaster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostForecaster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostForecasterList) DeepCopyInto(out *CostForecasterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CostForecaster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostForecasterList.
func (in *CostForecasterList) DeepCopy() *CostForecasterList {
	if in == nil {
		return nil
	}
	out := new(CostForecasterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostForecasterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostForecasterSpec) DeepCopyInto(out *CostForecasterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostForecasterSpec.
func (in *CostForecasterSpec) DeepCopy() *CostForecasterSpec {
	if in == nil {
		return nil
	}
	out := new(CostForecasterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostForecasterStatus) DeepCopyInto(out *CostForecasterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostForecasterStatus.
func (in *CostForecasterStatus) DeepCopy() *CostForecasterStatus {
	if in == nil {
		return nil
	}
	out := new(CostForecasterStatus)
	in.DeepCopyInto(out)
	return out
}
